In [18]:
import pandas as pd

Data1 = pd.read_excel(r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\6600 - 6800.xlsx")
Data2 = pd.read_excel(r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\DATASET SGK (2).xlsx")

Data2_sum_notnan = Data2[Data2['summary'].notna()].reset_index(drop=True)
Data2_sum_notnan

count = 0
for i in range(len(Data1)):
    for j in range(len(Data2_sum_notnan)):
        if pd.isna(Data1.at[i, 'output']) and str(Data1.at[i, 'title']).lower() == str(Data2_sum_notnan.at[j, 'title']).lower():
            count += 1
            Data1.at[i, 'output'] = Data2_sum_notnan.at[j, 'summary']
            break

print(count)
Data1

2298

,id,title,input,output,output_len,category,topic,source,grade,publisher
0,1.0,Tôi là học sinh lớp 2,"Ngày khai trường đã đến. Sáng sớm, mẹ mới gọi ...",Hôm nay là ngày khai trường. Tôi dậy rất sớm v...,NaN,NaN,",",NaN,Lớp 2,KẾT NỐI TRI THỨC
1,2.0,Ngày hôm qua đâu rồi?,Em cầm tờ lịch cũ:\n– Ngày hôm qua đâu rồi?\nR...,Em bé thắc mắc “Ngày hôm qua đâu rồi?” và đi h...,NaN,NaN,NaN,NaN,Lớp 2,KẾT NỐI TRI THỨC
2,3.0,Niềm vui của Bi và Bống,"Khi cơn mưa vừa dứt, hai anh em Bi và Bống chợ...","Sau cơn mưa, Bi và Bống nhìn thấy cầu vồng. Bi...",NaN,NaN,NaN,NaN,Lớp 2,KẾT NỐI TRI THỨC
3,4.0,Làm việc thật và vui,"Quanh ta, mọi vật, mọi người đều làm việc.\nCá...",Mọi vật xung quanh đều làm việc: đồng hồ báo g...,NaN,NaN,NaN,NaN,Lớp 2,KẾT NỐI TRI THỨC
4,5.0,Em có xinh không?,Voi em thích mặc đẹp và thích được khen xinh. ...,Voi em rất thích được khen xinh. Khi gặp hươu ...,NaN,NaN,NaN,NaN,Lớp 2,KẾT NỐI TRI THỨC
...,...,...,...,...,...,...,...,...,...,...
7479,NaN,Đạo giáo đã nảy sinh như thế nào?,"Đạo giáo (hay Lão giáo), Phật giáo và Hồi giáo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7480,NaN,Tại sao bệnh dịch hạch lại trở thành đại hoạ c...,"Ngày 24 tháng 3 năm 1345, người ta phát hiện t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7481,NaN,Đế quốc Ôt-tôman ra đời như thế nào?,"Giữa thế kỷ XIII, Tiểu Á rơi vào tình trạng hỗ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
7482,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7483,NaN,Tại sao Tần Thuỷ Hoàng được gọi là vị hoàng đế...,"Năm 221 trước Công nguyên, vua nước Tẩn là Doa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
Data1.to_excel(r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\data_abs.xlsx", index=False)

In [1]:
import pandas as pd
import re

txt_path = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\Cuongdata\New folder\Final\datalsthem.txt"
xlsx_path = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset extractive\datalsthem.xlsx"

# Đọc file txt
with open(txt_path, "r", encoding="utf-8") as f:
    text = f.read()

# Tách đoạn:
# \n\s*\n  -> dòng trống có thể chứa khoảng trắng
paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]

# Mỗi đoạn là một hàng
df = pd.DataFrame({
    "paragraph": paragraphs
})

# Ghi ra file Excel
df.to_excel(xlsx_path, index=False)

print(f"Đã chuyển {len(df)} đoạn văn sang {xlsx_path}")

Đã chuyển 1667 đoạn văn sang E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset extractive\datalsthem.xlsx

In [20]:
import pandas as pd
import re

txt_path = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset grade 5\Chan troi sang tao\van ban.txt"
xlsx_path = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset grade 5\Chan troi sang tao\outputvb.xlsx"

# Đọc file txt
with open(txt_path, "r", encoding="utf-8") as f:
    text = f.read()

# Tách các đoạn văn (dòng trống có thể chứa khoảng trắng)
paragraphs = [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]

titles = []
contents = []

for para in paragraphs:
    lines = [line.strip() for line in para.splitlines() if line.strip()]
    
    # Dòng đầu là tiêu đề
    title = lines[0]
    
    # Các dòng sau là nội dung
    content = "\n".join(lines[1:]) if len(lines) > 1 else ""

    titles.append(title)
    contents.append(content)

# Tạo DataFrame
df = pd.DataFrame({
    "title": titles,
    "content": contents,
    "publisher": "CHÂN TRỜI SÁNG TẠO"
})

# Ghi ra Excel
df.to_excel(xlsx_path, index=False)

print(f"Đã chuyển {len(df)} đoạn văn sang file {xlsx_path}")

Đã chuyển 8 đoạn văn sang file E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset grade 5\Chan troi sang tao\outputvb.xlsx

In [2]:
import pandas as pd

data = pd.read_excel(r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\Data DG.xlsx")
data_test = data
data_test

,title,content,summary,grade,publisher
0,"Bé Hà, bé Lê","Bé Lê ho, bà ạ.\nBà bế bé Lê.\nA, ba!\nBa bế c...",NaN,1,CÁNH DIỀU
1,"Bé Bi, bé Li","Bé Li bi bô:\nBi, Bi.\nBé ạ đi.\nBé ạ lia lịa,...",NaN,1,CÁNH DIỀU
2,Bể cá,"Ba Hà để bể cá ở hè. Bể có cá, có cò, le le. C...",NaN,1,CÁNH DIỀU
3,Ghế,Hà có ghế gỗ.\nBa Hà có ghế da.\nBờ hồ có ghế ...,NaN,1,CÁNH DIỀU
4,Bé kể,"Bà bế bé Lê. Bé bi bô: ""Dì... giò..."". Đó là b...",NaN,1,CÁNH DIỀU
...,...,...,...,...,...
2901,Bạn muốn lên Mặt Trăng?,Mặt Trăng xa hơn rất nhiều so với chúng ta tưở...,NaN,5,CÁNH DIỀU
2902,Ngày hội,Như trăm sông dồn biển\nBầu bạn tụ về đây\nThế...,NaN,5,CÁNH DIỀU
2903,Người được phong ba danh hiệu Anh hùng,"Cho đến nay, người Việt Nam duy nhất được phon...",NaN,5,CÁNH DIỀU
2904,Cô gái mũ nồi xanh,Đất Trung Phi chưa sạch mùi thuốc pháo\nThấp t...,NaN,5,CÁNH DIỀU
2905,con cú khôn ngoan,"Ngày xửa ngày xưa, có một con cú già sống trên...",NaN,5,CÁNH DIỀU

In [3]:
import re

def normalize_text(text):
    text = re.sub(r"([.,!?;:()])", r" \1 ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

for i in data_test['content']:
    print(normalize_text(i))

from vncorenlp import VnCoreNLP

rdrsegmenter = VnCoreNLP("../VnCoreNLP-master/VnCoreNLP-1.2.jar", annotators="wseg")

def word_segment(text):
    return rdrsegmenter.tokenize(text)

Bé Lê ho , bà ạ . Bà bế bé Lê . A , ba ! Ba bế cả Hà , cả bé Lê .
Bé Li bi bô : Bi , Bi . Bé ạ đi . Bé ạ lia lịa , bé bị ho . Bi dỗ bé .
Ba Hà để bể cá ở hè . Bể có cá , có cò , le le . Cò ở bể là có đá . Le le là le le gỗ .
Hà có ghế gỗ . Ba Hà có ghế da . Bờ hồ có ghế đá . Bà bế bé Lê ở ghế đá .
Bà bế bé Lê . Bé bi bô : "Dì . . . giò . . . " . Đó là bé kể : Dì Kế giả giò . Cỗ có giò , có gà , có cả giá đỗ .
Bi đó à ? Dạ Đố Bi : Mẹ có gì ? Mẹ có cá kho khế , Đố Bi : Bố có gì ? Bố có bé Li .
Nhà cô Nhã ở bờ hồ . Hồ nhỏ , nhà nho nhỏ , Hồ có cá mè , ba ba . Nhà có na , nho , khế .
Nhà có giỗ . Mẹ nhờ Bi dỗ bé Li . Bé nhè . Bi bế bé . Bé lơ mơ . Bi đi nhè nhẹ . Dỗ bé khó ghê cơ !
Nghỉ hè , Bi ở nhà bà . Nhà bà có gà , có nghé . Ổ gà be bé . Gà có ngô . Nhà nghé nho nhỏ . Nghé có cỏ , có mía .
Nhà dì Nga có pi a nô . Cả nhà Bi đi phố , ghé nhà dì , nghe pi a nô . Dì Nga pha cà phê . Bố mẹ có cà phê . Bi có phở . Bé Li có na .
Quế có bà ở quê . Khi bà ra phố , cả nhà có quà . Quà là rổ khế , rổ mơ , cá rô , cá quả . Có khi là cô gà ri .
Nhà sẻ có sẻ bé . Sẻ ca "ri . . . ri . . . " . Phía xa là nhà quạ . Quạ la" quạ . . . quạ . . . " . Sẻ bé sợ quá . Sẻ bố dỗ : "Sẻ ca ri ri . Qua la quạ quạ . Bé sợ gì ! " .
Bi có bà ở quê . Nghỉ hè , Bi ở nhà bà . Xa nhà , Bi nhớ bố mẹ . Giá bà ra phố ở nhà Bi , Bi đỡ nhớ bà , nhớ bố mẹ .
Bố Thơ là thợ mỏ . Bố ở xa nhà . Ở nhà có mẹ , có Thơ , có bé Tộ , Cả nhà nhớ bố .
Chị Trà cho bé Chi đi nhà trẻ . Qua chợ , chị chỉ cho bé cá trê , cá mè , . . . Ở nhà trẻ , Chi nhớ mẹ . Chị Trà dỗ : "Bé nhè thì cô chê đó . " . Bé nghe chị .
Chó xù lừ lừ đi ra ngõ . Lũ gà ngỡ nó là sư tử , sợ quá . Sư tử đi qua . Nó ngó chó xù : Mi mà là sư tử à ? Chó xù sợ quá : Dạ . . . chỉ là chó xù ạ .
Bữa đó , thỏ ra bờ hồ . Xa xa có chú rùa . Thỏ đùa , rủ rùa thi đi bộ . Rùa chả sợ : "Thi thì thi ! " . Thỏ nghĩ : "Cứ để rùa bò . Ta phi như gió . Sợ gì ! " .
Thỏ nghĩ rùa sẽ thua . Nó la cà chỗ nọ , chỗ kia . Rùa tự nhủ : "Ta sẽ cố . " . Giữa trưa , rùa đã bỏ xa thỏ , Thỏ thua rùa .
Dì Tư là y tá . Trưa qua , dì ra y tế xã . Khi về , dì ghé nhà Hà . Dì chỉ cho Hà vẽ , Hà vẽ lá , vẽ ve . Hà vẽ cả bé Lê .
Má ở thị xã về . Má có quà cho cả nhà . Bà có nho . Ba có trà . Hà có mía . Bé Lê có sữa . Ơ , quà của má là gì nhỉ ? À , má đã có bé Lê , có Hà là quà quý .
Bố mẹ cho Giáp và bé Lam đi phố cổ . Cả nhà đi bộ ra Bờ Hồ . Gió hồ nhè nhẹ . Bố chỉ cho cả nhà Tháp Rùa ở giữa hồ .
Bà bị cảm . Cả nhà lo lắm . Mẹ đi khắp chợ mua lá để chữa cảm . Ở nhà , bố và Thắm pha sữa cho bà . Có cả nhà chăm , bà đã đỡ .
Bé Chi chăm chỉ lắm . Bé đi khắp nhà . Khi thì bé mở vở của chị , ê a . Khi thì bé đi xe đạp . Khi thì bé khám cho chó Lu . Lu "gừ gừ" có vẻ thú vị lắm .
Bé Lê mê ti vi . Ti vi có sâm cầm . Bé chỉ : "Cò . . . Cò . . . " . Ti vi có cá mập . Bé la : "Sợ ! " . Má bế bé , vỗ về : "Cá mập ở ti vi mà . " . Má ấm quá , bé chả sợ nữa .
Cá chép và gà nhí thi vẽ . Cá chép vẽ nó làm vua . Gà nhí vẽ gà mẹ chăm lũ gà em . Cô cò , chú trắm chấm thi . Họ cho là gà nhí vẽ vừa đẹp vừa có ý nghĩa .
Lúa tẻ cho là nó thua kém lúa nếp vì trẻ em chỉ ưa đồ nếp . Đêm đó , nghe lúa tẻ thổ lộ , lúa nếp đáp : Chị nhầm . Lúa tẻ là vua cả năm . Đồ nếp chỉ là bữa phụ .
Sẻ gặp cò ở hồ . Sẻ chê mỏ cò thô . Cò chả đáp gì . Sẻ rủ cò qua bờ kia . Gặp gió to , sẻ chìm nghỉm . Cò kịp thò mỏ gắp sẻ , đưa sẻ qua hồ . Từ đó , sẻ chả dám chê cò ,
Đêm ở quê quả là êm ả . Ở thị xã , cả đêm ì ầm ô tô , xe lửa . Ở quê chỉ nghe gió thở , tre rì rầm , dế rỉ rả . Có chú bìm bịp nấp ở đám cỏ cứ "íp bịp , íp bịp" .
Trưa hè , gà nhí nằm mơ bị quạ cắp đi . Gà nhí sợ quá . Nó "chiêm chiếp" ầm ĩ . Gà mẹ khe khẽ ru . Mẹ ru êm quá , Gà nhí ngủ thiếp đi .
Lừa và ngựa đi xa . Lừa còm nhom mà chở lắm đồ quá . Lừa nhờ ngựa chở đỡ . Ngựa chả nghe . Vì cố quá , lừa ngã ra bờ cỏ . Thế là bà chủ xếp đồ từ lừa qua ngựa .
Chó thì mổ mổ Gà thì liếm la Dữ như quả na Nhu mì gã cọp Cò thì phốp pháp Bò thì ốm o Cá thì la to Im như trẻ nhỏ Chậm như cô thỏ Lẹ như cụ rùa . . .
Chị Thơm ra đề : "Cặp của Bi có quả cam . . . " . Bị đáp : Em chả đem cam ra lớp . Chị ví dụ mà . . . Chị tiếp nhé : Bi cho em Bốp 1 quả . . . Chị nhầm ạ . Em Bốp chỉ bú mẹ . Thì chị ví dụ mà . . .
Rùa nhí đi tìm chỗ ở . Nó vừa bò vừa nơm nớp lo gặp thú dữ . Gặp thỏ , rùa lập bập : Tớ chưa có nhà . Thỏ khà khà : Ri rà rì rà . Đem nhà đi phố . Rùa nhớ ra chưa ? Rùa ngớ ra : Ừ nhỉ .
Lớp cũ họp ở khóm tre ngà . Cả lũ kể le rôm rả . Sẻ kể : Tổ của nó nhỏ mà đẹp lắm . Gà kể : Nó chăm lũ gà nhỏ như nắm rơm . Cua khệ nệ ôm yếm . Nó sắp có lũ cua bé tí bò khắp hồ .
Mẹ ở thị xã về , mua dép cho bé Chi . Dép đẹp quá . Khi Chi đi , dép cứ "chíp , chíp , chíp , chíp" . Quả là thú vị . Chi mê dép lắm . Hôm đó , từ sớm , Chi đã tìm chị Trà : Đêm qua em nằm mơ , dép "chíp , chíp" của em bị chó Lu tha đi . Em nhờ chị tìm . Thế chị đã tìm ra dép cho em chưa ? Chị Trà ngớ ra : Ơ , đó là em nằm mơ chứ ? Khi em mơ có chị ở đó . Chị đã hứa tìm dép hộ em mà . Chị Trà ngó khắp nhà : Ồ , dép của em ở gầm ghế kia kìa ! Chi nhòm nhòm gầm ghế , la to : Đó , chị đã hứa tìm là chị sẽ tìm ra mà .
Khỉ đi thăm bà . Khi đi , nó hứa sẽ đem về đủ thứ cỏ lạ quả thơm làm quà cho thỏ và nhím . Thế mà khi về , nó chả nhớ nó đã hứa gì . Về nhà , khỉ chả có thứ quà gì như đã hứa . Nó chả dám gặp thỏ và nhím . Có gặp thì chỉ nghe thầm thì : "Khi hứa mà chả làm . " . Trưa đó , khỉ kể cho mẹ nghe . Mẹ nó thủ thị : Đã hứa thì cố mà làm . Hứa mà chả làm gì thì tệ quá . Nghe mẹ , khỉ tìm gặp thỏ và nhím . Nó hứa sẽ sửa chữa .
Cò vừa ngủ thì nghe om sòm "chiếp , chiếp" , "quạ , quạ" . Thì ra quạ sắp chộp gà nhí . Qua to và dữ . Gà thì bé tí , nép ở khóm tre . Cò vù qua khóm tre . Nó che cho gà , chĩa mỏ về phía quạ . Quạ sợ , bỏ đi .
Hà nhỏ mà chăm chỉ . Hà giúp bà xếp đồ ở tủ . Hà nhổ đám cỏ um tùm ở ngõ . Có hôm , Hà giúp bà chữa mũ cho búp bê . Ngắm Hà chăm chú đưa chỉ qua lỗ kim , bà tủm tỉm : "Hà của bà ngộ quá ! " .
Ở Thủ đô có phố Thợ Nhuộm . Bà em kể , xưa kia , phố có nghề nhuộm . Phố tấp nập và đẹp lắm . Bà hứa đưa em đi thăm phố . Bà sẽ kể cho em nghe thêm về nghề nhuộm .
Gió mùa về . Mẹ mua cho bà tấm nệm ấm , vì tấm nệm cũ có chỗ đã tướp ra . Đêm đó , Mi nằm ôm bà ngủ . Bà thì thầm : "Bé Mi của bà ấm quá ! Ấm như bếp lửa đỏ đượm . " .
Giàn mướp nhà Hà vừa ra nụ đã thơm ngát . Lắm hôm , Hà vừa đếm nụ vừa khe khẽ hát cho giàn mướp nghe . Có cả đàn bướm về tụ họp . Có lẽ nhờ thế mà mùa hè năm đó , giàn mướp sớm ra quả .
Quạ ghé xóm gà . Gà mơ ngờ ngợ : "Quạ la cà làm gì ? " . Sớm ra , gà tía la om sòm : "Có trộm ! " . Gà mơ than : "Có kẻ đã tha gà nhí đi . " . Vừa khi đó , thám tử gà cồ tóm cổ quạ . Cả xóm ùa ra , quạ sợ quá .
Nhà Hà có bà và ba má . À , có cả Hà và bé Lê nữa chứ . 6 giờ , Hà giúp má sắp cơm . Ba cho gà ăn . Bà rửa mặt cho bé Lê . Kế đó , cả nhà ăn cơm . 7 giờ , ba má dắt xe đi làm . Hà ra lớp . Bà đưa bé Lê đi nhà trẻ .
Chủ nhát , bố mẹ Bi ở nhà . Mẹ làm phở bò . Bố giặt giũ . Bi cho gà ăn . Bé Li rửa mặt , rửa chân cho búp bê . Cả nhà ăn phở . Mẹ ăn chậm nhất vì vừa ăn vừa cho bé Li ăn . Bi phụ bố rửa bát . Mẹ thì xem vở của Bi , gật gù : "Bi khá lắm ! " .
Nhà Bi ở phố Lò Rèn . Xưa kia cả phố làm nghề rèn . Giờ chỉ có dăm nhà giữ nghề cũ . Giữa phố xá nhà cửa san sát mà lò rèn đỏ lửa như ở chợ quê . Búa đập chan chát . Bễ thở phì phò . Lửa than khét lẹt .
Nhà Bi về quê ăn Tết . Xe về bến chậm . Mẹ phàn nàn : "Chậm như sên ! " . Đêm 30 , cả nhà làm lễ bên bàn thờ . Bố lầm rầm khấn . Bà chấm chấm khăn lên mắt . Cả năm bà đã chờ nhà Bi về sum họp bên mâm cơm Tết .
Chủ nhật , bố mẹ đưa Vân về quê thăm bà . Gần nhà bà có bạn Tâm . Vân và Tâm kết bạn . Bà dẫn Vân và Tâm đi xem gặt lúa . Vân kể cho Tâm nghe về phố xá tấp nập .
Gần nhà Ngân có hồ sen đẹp lắm . Từ của sổ , Ngân có thể nhìn rõ mặt hồ . Mùa hè đến , sen ra búp . Chỉ ít hôm , sen đã nở kín hồ . Khi gió về , nhà Ngân thơm ngát .
Lớp Hà có tiết tập viết . Hà viết rất cẩn thận . Thế mà bạn Kiên xô bàn làm chữ "biển" của Hà xiên đi , Hà nhăn mặt . Kiên thì thầm : "Tớ lỡ mà . " . Hà chả giận bạn . Em viết thêm chữ "biển" thật đẹp . Cô nhìn chữ em , khen : "Chữ Hà đẹp lắm ! " .
Nam Yết nằm giữa biển , như nét chấm nhỏ trên bản đồ Việt Nam . Từ xưa , Việt Nam đã làm chủ Nam Yết . Nam Yết có nhà cửa , có đèn biển . Chiến sĩ ở đó như ở nhà . Nam Yết là bộ phận của cơ thể Viết Nam .
Rô mẹ đi kiếm ăn , dặn con : Con ở nhà , chớ đi xa nhé . Rô con "dạ" rõ to . Mẹ vừa đi , rô con liền tót ra ngõ . Nó rủ cá cờ lên bờ xem ở đó có gì lạ . Cá cờ can : Mẹ bạn dặn chớ đi xa mà . Rô con đáp : Bờ hồ gần lắm .
Rô con vọt lên bờ . Chả ngờ , bờ hồ khô cạn , nó nằm thở . Chị gió nghe rô than thở , bèn đi tìm thần mưa . Thần mưa phất cờ . Mưa to đổ về , tràn qua bờ hồ . Rô con vót về nhà . Nó xin mẹ tha thứ .
Chi bị sốt . Mẹ đưa bé lên trạm y tế . Cô y tá tiêm cho Chi . Chi vẫn nằm thiêm thiếp . Mẹ hôn lên trán Chi . Nụ hôn của mẹ thật ấm áp . Chi từ từ mở mắt , thì thầm : Mẹ à , con chả ốm nữa . Mẹ sở trán Chi . Bé đã hạ sốt .
Giờ kiểm tra . Sơn vừa chép để vừa lẩm nhẩm : "Giỏ có 8 con cá thờn bơn . Cho bớt 5 con , còn 4 . " . Hà thì thầm : "Còn 3 chứ ? " . Cô Yến đến bên Hà : Hà để bạn tự làm đi . Hà lễ phép : Dạ . Sơn ngẫm nghĩ . Em chợt nghĩ ra và nắn nót viết : "8-5=3" .
Thỏ rủ cún làm mứt cà rốt . Cún đun bếp , lửa ngùn ngụt . Thỏ la : Lửa to quá ! Rút bớt lửa đi ! Bạn la to làm tớ sợ quá . Cún phàn nàn . Thỏ nhỏ nhẹ : Làm mứt cần nhỏ lửa , cún à . Thế à ? Cảm ơn thỏ nhé .
Mẹ bận làm bếp . Chuột út buồn , lũn cũn đi ra sân . Đến trưa , về nhà , nó ôm mẹ , kể : Mẹ ạ , trên sân có một con thú dữ lắm . Mũ nó đỏ , mỏ nhọn , mắt thô lố . Nó quát rõ to . Con sợ quá . Chuột mẹ đáp : Con thú đó rất hiền . Nó chỉ muốn đùa con .
Chuột út hớn hở kể tiếp : Con còn gặp một con thú rất hiền . Nó nằm thu lu trên sân . Nó luôn liếm chân , liếm cổ và nhìn con rất thân thiện . Chuột mẹ la lớn : Đó là kẻ thù của nhà chuột . Con mà đến gần , nó sẽ ăn thịt con đó .
Cún , thỏ và vượn ra biển . Biển đẹp quá . Trên bờ , lũ chuột trượt ván , nô đùa ầm ĩ . Trên mặt biển , bọn cá chuồn hăm hở lướt đi . Đến lượt cún , nó lướt như múa lượn . Vượn chưa dám ra xa . Thỏ sợ ướt , ở trên bờ cổ vũ . Gần trưa , ba bạn về nhà . Ra biển thú vị thật !
Nàng tiên cá là con vua biển . Nửa thân trên của nàng như một cô bé . Nửa thân kia là cá . Nhờ thế , nàng lướt trên biển rất nhẹ nhàng . Nàng tiên cá có tất cả các thứ nàng muốn . Nàng chỉ chưa biết đất liền . Đêm đêm , nàng ngân ngã hát . Dân đi biển nghe nàng hát , quên cả mệt , cả buồn .
Ở biển lớn , có một chú cá măng nhỏ . Sáng sáng , mẹ dẫn chú đi kiếm ăn . Một hôm mưa to gió lớn , cá măng lạc mẹ . Cá măng lo lắng lắm . Chú đang cố tìm mẹ thì từ đằng xa , chợt hiện ra một con cá mập . Mồm cá mập há to , răng sắc nhọn , lởm chởm .
Cá mập áp sát cá măng . Cá măng bèn nhô lên , bám chặt thân trên cá mập . Tự nhiễn mất hút cá măng , cá mập ngớ ra : "Ta đã ăn nó chưa nhỉ ? " . Cá măng bỏ cá mập , tìm về nhà . Chợt mẹ nó vụt đến như một giấc mơ . Nó áp sát mẹ , cảm giác lâng lâng khó tả .
Có bác thợ săn gặp một con vượn mẹ đang cho con bú . Bác rút tên , ngắm . Vượn mẹ chợt ngẩng lên . Nó nhìn bác , mặt đờ ra . Bác thợ săn nghĩ : "Ta bắn nó , con nó sẽ chết . " . Thế là bác bỏ đi . Từ đó , bác bỏ nghề săn bắn .
Sáng sáng , xe rác lặng lẽ đi làm . Nó về khi tất cả đã ngon giấc . Xe điện , xe téc cằn nhằn : "Bẩn quá ! " . Một đêm mưa to , phố xá ngập rác . Xe điện , xe téc lo lắng nhìn . Thế mà sáng sớm , phố xá đã hết rác . Nhìn xe rác bon bon chở rác , xe téc hòn hở , xe điện leng keng : "Cảm ơn bạn nhé ! " .
Cô xẻng làm việc rất siêng năng . Có lần , chị gió hăm hở dọn đỡ cô . Chả ngờ , gió làm rác văng khắp chốn . Chị gió buồn lắm . Nhìn chị gió ủ rũ , cô xẻng nhẹ nhàng : Chị chớ buồn . Chị luôn giúp nhà nhà mát mẻ mà . Chú yểng nghe thế thì lem lém : Em siêng năng , chị chăm chỉ .
Sóc , nhím và thỏ ngọc Học lớp cô sơn ca Bác ngựa đón từ nhà Đưa cả ba đi học . Vó ngựa va lóc cóc Xe cứ lăn bon bon Chim chóc liệng vòng tròn Hát ca vang rộn rã . Đi học lắm sự lạ Cha mẹ vẫn chờ mong Ba bạn hứa trong lòng Học tập thật chăm chỉ .
Xưa kia , quạ và công trắng muốt . Một hôm , quạ rủ công làm đẹp . Quạ trang điểm cho công . Xong , nó nhìn công , gật gù : Đẹp quá ! Giờ đến lượt tớ . Chợt có tiếng lợn "eng éc" . Làng bên có cỗ . Quạ sốt ruột . Nó dốc hết lọ bột đen đã pha lên thân . Từ đó , quạ đen như than .
Ông ở quê ra , tặng Long một con yểng đẹp lắm . Lông nó đen biếc , mỏ đỏ , cổ có sọc vàng . Yểng biết hót "Ông ạ ! " , khiến Long mê tít . Long muốn yểng hót : "Long à ! " . Chín hôm liền , cứ học xong là Long đến bên lồng yểng , thủ thỉ : "Long à ! " . Thế là yểng bỗng cất tiếng : "Long à ! " .
Sáng sớm , gà mẹ dẫn đàn con ra vườn kiếm ăn . Bất chợt mưa to , gió lớn . Đàn gà con rét run . Gà mẹ liền ôm các con , ấp ủ chúng . Rúc trong lòng mẹ , đàn gà con cùng chiêm chiếp : "Mẹ ấm quá ! Ấm quá ! " .
Sáng sớm , biển thật là đẹp ! Từ phía xa tít tắp , một vầng hồng từ từ nhô lên . Mặt biển ủng hồng . Từng lớp sóng nhấp nhô . Những tia nắng sớm nô đùa trên sóng . Nắng lên dần . Mặt biển sáng rực .
Công cho rằng nó đẹp nhất trần gian . Một hôm , công ưỡn ngực đến bên hồ . Nó bỗng nhận ra trong hồ có một con công khác . Nó bèn sà xuống hồ để so sắc đẹp . Nhưng nó vừa xuống , con công kia đã biến mất . Công ngụp lặn tìm . Nó ướt nhạp , run cầm cập . Chim cuốc nhìn công , gật gù : "Đẹp mà chẳng khôn ! " .
Một hạt giống nhỏ nằm lặng lẽ bên đường . Bé nhặt được , đem về thả xuống góc vườn . Chỉ ít hôm , mầm non đã vươn lên , uống những giọt sương sớm . Lá non khẽ rung rung . Dường như là muốn cảm ơn bé .
Ông bà em rất thương em . Sáng sáng , ông đưa em đến trường . Hết giờ học , ông đón em về . Khi em về đến nhà , bà pha nước để ông bà và em cùng uống . Em uống nước và kể cho ông bà nghe về các bạn ở trường .
Chồn và gà rừng là bạn thân nhưng chồn vẫn ngầm xem thường gà . Một hôm , chồn tỏ vẻ : Gà à , bạn có trí khôn chứ ? Chỉ có tí ti . Gà đáp , Chồn ra vẻ : Tớ thì có cả trăm trí khôn cơ . Vừa lúc đó , một bác nông dân cầm liềm đi qua . Chồn và gà cuống cuồng bỏ trốn . Chúng nấp trong đám cỏ rậm . Bác nông dân len giữa đám cỏ , đe : "Ta đã nhìn rõ bọn mi . Cứ nằm yên đó nhé ! " . Chồn và gà nghe thế thì ớn quá . Gà giục chồn : "Bạn nghĩ kế gì đi ! " . Chồn chả nghĩ ra kế gì . Nó nhờ gà nghĩ giúp . Gà thầm thì : "Bạn cứ yên trí làm thế , làm thế . . . " . Bác nông dân tóm được gà trong đám cỏ . Gà giả vờ ủ rũ . Bác ta bỏ gà trên cỏ để vồ chồn . Gà vù lên đống rơm , vươn cổ : "O ó o . . . " . Bác liền bỏ chồn để vồ gà . Chỉ chờ thế , chồn co giò biến mất . Chồn về đến nhà , vừa sợ , vừa thẹn , vừa cảm phục gà . Chồn đến tìm gà . Nó ân hận : Gà à , tí ti trí khôn của bạn còn hơn cả trăm trí khôn của tớ . Cảm ơn bạn nhé ! Từ hôm đó , chồn tin và quý gà hơn .
Những đêm trăng , bà thường chỉ chi Bi ba bóng đen mờ trên Mặt Trăng . Trông chúng giống một gốc đa , một con nghé và một chú bé . Bà kể : Xưa kia chú bé ở trần gian . Một cơn gió đã cuốn chú cùng gốc đa và nghé lên cung trăng . Trên đó , chú rất buồn vì nhớ nhà . Nhưng mặt đất quá xa . Chú bé không về được nữa .
Đêm đến , khi đám trẻ tụ tập bên bàn thì thần ru ngủ rón rén bước đến . Thần hé của , phả một làn gió nhẹ . Thế là bọn trẻ buồn ngủ rũ . Khi bọn trẻ ngủ , thần che chiếc ô có bức vẽ đẹp cho những đứa trẻ dễ thương . Các bé sẽ có giấc mơ đẹp . Đứa trẻ hư chẳng mơ gì vì chiếc ô che cho chúng không vẽ gì .
Từ khi Thanh còn bé , ba má đã mua cho em những cuốn sách có tranh ảnh đẹp . Thanh chưa biết chữ nên chỉ xem tranh . Tranh thì vẽ bạn sóc hiền lành . Tranh thì vẽ cô gà "cục tác" , chú lợn "ủn ỉn" , . . . Giờ thì Thanh đã có một tủ sách . Nhờ có sách , em học đọc rất nhanh .
Mưa đổ xuống . Các con vật tìm chỗ trú mưa . Bọ dừa trốn mưa nhờ đám lá dừa . Cánh cam tránh mưa ở khóm lúa . Chim sẻ nấp ở cành chanh . Kiến nép bên gốc nấm . Nấm như một chiếc ô che cho nó . Ếch và ễnh ương không sợ mưa .
Trên bàn học của Bích có cuốn lịch bàn . Đó là một cuốn lịch rất đẹp . Bìa lịch in hình vịnh Hạ Long . Cuốn lịch vừa giúp Bích biết năm tháng vừa trang trí cho bàn học của em . Cuốn lịch nhắc Bích chăm chỉ học hành , không để thì giờ lãng phí .
Sáng sáng , gà trống gáy vang . Nghe tiếng gáy , ai cũng tỉnh giấc . Vì thế , gà trống cho là mình rất quan trọng . Chú ưỡn ngực , đi đi lại lại . Chú ra lệnh cho gà mái mơ : "Cô dọn cái rác này đi ! " . Tiếp đó , lại quay sang gà mái vàng : "Chị đã cho bọn trẻ ăn chưa ? " . Cứ thế , chú sai khiến , dạy dỗ tất cả .
Một hôm , lũ gà mái trốn sạch . Gà trống không có ai để ra lệnh , rất buồn . Nhìn bác chó đang nghếch mõm , nằm dài trên sân tắm nắng , chú bèn lại gần , lay lay : " Đi làm đi ! " . Bác chó túc mình , tạp cho một cái . Gà trống sợ hết hồn , chạy mất . Từ đó , chú chả dám hạch sách ai nữa .
Dê con đang gặm cỏ , bỗng thấy sói ở ngay trước mặt . Dù rất sợ , dê vẫn bình tĩnh nói : Để bác ngon miệng , con hát tặng bác một bài nhé ? Sói đồng ý . Dê con bèn lấy hết sức hét : "Be . . . be . . . " . Ông chủ đang ở gần đó nghe thấy , liền vác gậy chạy lại , nện sói một trận nên thân .
Con bướm trắng Lượn vườn hồng Gặp con ong Đang bay vội Bướm liền gọi Rủ đi chơi Ong trả lời Tôi còn bận Mẹ tôi dặn Việc chưa xong Đi chơi rong Mẹ không thích .
Mẹ Mặt Trời thả hạt nắng xuống đất chơi . Hạt nắng gặp bông hồng bị gãy cành đang sụt sùi khóc . Nó an ủi , rồi gửi tặng bông hồng chiếc khăn vàng óng . Nghe hạt mầm thì thầm , nó phả hơi ấm xuống đất . Thế là mầm cây đội đất nhô lên . Khi mẹ Mặt Trời gọi , hạt nắng bám cánh tay hồng của mẹ về bên kia núi .
Cá bơi dưới suối , thấy chim hót trên cây , bèn rủ : Này bạn chim ơi ! Chim có biết bơi Xuống đây mà chơi Thích lắm ! Thích lắm ! Chim trả lời : Ôi bạn cá ơi ! Chim không biết bơi Chim có đôi cánh Chim bay trên trời . Cá nói : Không lo chim ơi ! Cá bơi dưới suối Chim bay trên trời Ta cùng đi chơi Thích lắm ! Thích lắm ! Thế rồi hai bạn cùng đi chơi .
Mờ sáng , vịt đã đến gọi gà : Dậy tập bơi đi , gà ơi ! Có tiếng gà : Tớ đi vắng rồi . vịt nói : Tớ định tập bơi xong sẽ đi kiếm giun . Gà vội ra khỏi chuồng : Cho tớ đi kiếm giun với ! Đợi tớ tập bơi xong đã nhé ! Thế là , chỉ vì lười mà tới nay gà vẫn không biết bơi .
Biết mèo sẵn giỏi , hổ đến xin học . Mèo giao hẹn : Ta sẽ dạy . Nhưng anh không được bắt lũ thú Hổ đồng ý . Nhưng vừa học được cách vồ mồi , nó đã săn thỏ , Thế là mèo không dạy hổ nữa . Hổ nghĩ tài nó đã cao . Tối đó , nó chờ mèo đi qua , lao ra vồ . Mèo leo tót lên cây , bảo : Mẻo mèo meo ! Ta có võ trèo , ta chưa dạy hổ .
Mẹ sai thỏ nâu ra vườn nhổ cà rốt . Mẹ bảo : "Nhổ sáu củ , con nhé ! " . Củ cà rốt nằm sâu dưới đất , nhưng nhổ không khó . Hấp ! Hấp ! Một lát sau , thỏ nâu đã nhổ được cả ôm . Nó chạy vào bếp đưa cho mẹ . Không ngờ , thỏ mẹ la lên . Thì ra thỏ nâu nhổ lắm quá . Nó gãi đầu : "Hì ! Con chưa biết đếm mà . " .
Ngày xưa , ở làng kia có một chàng đốn củi nghèo . Tài sản của anh chỉ có chiếc rìu sắt . Một hôm , anh vào rừng đốn củi . Chẳng may , lưỡi rìu văng xuống sông . Buồn quá , anh ngồi khóc . Bỗng có một ông lão đến , hỏi : "Vì sao con khóc ? " . Anh mếu mạo trả lời . Ông lão bèn lặn xuống sông , mang lên một lưỡi rìu bạc .
Chàng tiễu phu không nhận lưỡi rìu bạc là của mình . Ông lão lại lặn xuống sông , mang lên một lưỡi rìu vàng . Anh vẫn lắc đầu . Cuối cùng , ông lão mang lên một lưỡi rìu sắt . Anh reo lên , nhận đó là chiếc rìu yêu quý của mình . Ông lão nói : "Ta là Bụt . Con túng thiếu mà không tham . Ta thưởng cho con lưỡi rìu vàng và bạc này . " .
Có bác đánh cá nghèo câu được con có bé xíu . Cá van xin : Tôi là cá thần . Bác thả tôi ra , tôi sẽ tặng bác một điều ước . Bác liền thả cá . Cá nói : Cảm ơn bác . Bác ước gì nào ? Bắc đánh cá nói : Tôi ước muốn gì được nấy . Cá trả lời : Bắc tham quá nên sẽ chẳng được gì đâu . Thế là bác đánh cá vẫn nghèo như xưa .
Hươu ra suối chơi . Sói mò tới . Cừu thấy vậy , be to : "Có sói ! " . Nghe tiếng cừu , hươu co giò chạy . Sói thấy vậy , lao tới vồ cừu . Cừu kêu : Cứu tôi với ! Khướu đậu trên ngọn cây , thấy thế , la to : Hổ tới kìa ! Sói sợ hổ , bỏ cừu , chạy mất . Hươu , cừu , khướu từ đó thân nhau .

In [20]:
from collections import defaultdict
import pandas as pd

data = pd.read_excel(r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\Data TX.xlsx")
data_test = data
grade_vocab = defaultdict(set)

for _, row in data_test.iterrows():
    tokens = word_segment(normalize_text(row["content"]))
    for sent in tokens:
        for word in sent:
            grade_vocab[row["grade"]].add(word.lower())

len(grade_vocab)

5

In [24]:
import os

output_dir = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\grade_vocab"
os.makedirs(output_dir, exist_ok=True)

from collections import defaultdict

cumulative_vocab = defaultdict(set)

sorted_grades = sorted(grade_vocab.keys())

current_vocab = set()

for grade in sorted_grades:
    current_vocab |= grade_vocab[grade]   # union
    cumulative_vocab[grade] = current_vocab.copy()

for grade, vocab in cumulative_vocab.items():
    file_path = os.path.join(output_dir, f"grade_{grade}.txt")
    with open(file_path, "w", encoding="utf-8") as f:
        for word in sorted(vocab):
            f.write(word + "\n")

In [3]:
import pandas as pd
import re

txt_path = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\data035.txt"
xlsx_path = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\data3.xlsx"

# Đọc file txt
with open(txt_path, "r", encoding="utf-8") as f:
    text = f.read()

# Tách các đoạn văn (dòng trống có thể chứa khoảng trắng)
paragraphs = [p.strip() for p in re.split(r"\n\n", text) if p.strip()]

titles = []
contents = []

for para in paragraphs:
    lines = [line.strip() for line in para.splitlines() if line.strip()]
    
    # Dòng đầu là tiêu đề
    title = lines[0]
    
    # Các dòng sau là nội dung
    content = "\n".join(lines[1:]) if len(lines) > 1 else ""

    titles.append(title)
    contents.append(content)

# Tạo DataFrame
df = pd.DataFrame({
    "title": titles,
    "content": contents
})

# Ghi ra Excel
df.to_excel(xlsx_path, index=False)

print(f"Đã chuyển {len(df)} đoạn văn sang file {xlsx_path}")

Đã chuyển 86 đoạn văn sang file E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\data3.xlsx

In [5]:
from vncorenlp import VnCoreNLP
import pandas as pd
vncorenlp = VnCoreNLP(
    r"../../VnCoreNLP-master/VnCoreNLP-1.2.jar",  # chỉnh đúng path của bạn
    annotators="wseg",
    max_heap_size='-Xmx2g'
)

df = pd.read_excel(r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\DATA_DG_main.xlsx")

def count_sentences_and_words(text):
    if not isinstance(text, str) or text.strip() == "":
        return 0, 0

    sentences = text.split(".")
    sentences = [s.strip() for s in sentences if len(s.strip()) > 0]

    word_count = 0
    for sent in sentences:
        tokens = vncorenlp.tokenize(sent)
        word_count += sum(len(s) for s in tokens)

    return len(sentences), word_count
df_g1 = df[(df["grade"] == 3) & (df["publisher"].notna())].copy()
df_g1["num_sentences"] = 0
df_g1["num_words"] = 0

for idx, row in df_g1.iterrows():
    sents, words = count_sentences_and_words(row["content"])
    df_g1.at[idx, "num_sentences"] = sents
    df_g1.at[idx, "num_words"] = words
max_sent_row = df_g1.loc[df_g1["num_sentences"].idxmax()]

print("📌 Văn bản có nhiều câu nhất (grade=1)")
print("Số câu:", max_sent_row["num_sentences"])
print("Số từ:", max_sent_row["num_words"])
print("Nội dung:\n", max_sent_row["content"])

max_word_row = df_g1.loc[df_g1["num_words"].idxmax()]

print("📌 Văn bản có nhiều từ nhất (grade=1)")
print("Số câu:", max_word_row["num_sentences"])
print("Số từ:", max_word_row["num_words"])
print("Nội dung:\n", max_word_row["content"])

📌 Văn bản có nhiều câu nhất (grade=1)
Số câu: 37
Số từ: 434
Nội dung:
 HƯỚNG DẪN
Bước 1: Nháy đúp chuột vào biểu tượng The PC trên màn hình nền. Cửa sổ This PC mở ra có dạng như Hình 51.
Bước 2:
Nháy chuột vào This PC ở khung bên trái, quan sát khung bên phải.
Nháy đúp chuột vào ổ đĩa D: ở khung bên phải, quan sát để xem bên trong ở đĩa D: chứa gì.
NHIỆM VỤ 2 Thực hiện thao tác với thư mục.
Tạo thư mục mới theo cây thư mục ở Hình 52.
Đổi tên thư mục Do-re-mon thành Hoang tu Ech.
Xoá thư mục Co-nan
HƯỚNG DẪN
a) Tạo một thư mục mới.
Bước 1: Trong khung bên trái của cửa sổ This PC, em nháy chuột vào ổ đĩa D:
Bước 2: Trong dải lệnh Home, chọn lệnh New folder ở Hình 53.
Bước 3: Thư mục mới có tên mặc định là New folder ở Hình 54. Gõ tên thư mục, chẳng hạn là Truyện tranh. Nhấn phím Enter để kết thúc.
Sau bước này, em đã tạo thư mục Truyện tranh
trên ổ đĩa D:. Tương tự, em tạo thêm thư mục Truyện co tich ở ổ đĩa D:.
Bước 4: Nháy đúp chuột vào thư mục Truyện tranh ở khung bên phải để mở thư mục Truyện tranh. Tạo tiếp các thư mục mới là Do-re-mon, Trang Quynh và Co-nan.
b) Đổi tên thư mục Do-re-mon thành Hoang tu Ech.
Bước 1: Nháy chuột vào thư mục Do-re-mon để chọn.
Bước 2: Trong dải lệnh Home, chọn lệnh Rename ở Hình 55.
Bước 3: Gõ tên mới Hoang tu Ech. Nhấn phím Enter để kết thúc.
c) Xoá thư mục Co-nan.
Bước 1: Nháy chuột vào thư mục Co-nan.
Bước 2: Trong dải lệnh Home, chọn lệnh Delete ở Hình 57 (có thể nhấn phím Delete trên bàn phím).
Lưu ý: Em hãy cân nhắc kĩ trước khi quyết định xoá thư mục để tránh mất thông tin.
NHIỆM VỤ 3 Tìm tệp ở thư mục cho trước theo yêu cầu.
HƯỚNG DẪN
Bước 1: Mở cửa sổ This PC.
Bước 2: Lần lượt mở các thư mục theo yêu cầu để đến được tệp cần tìm. Ta có thể mở các thư mục và thư mục con ở khung bên trái hoặc nháy đúp vào mỗi thư mục ở khung bên phải.
Ví dụ, để tìm tệp Anh.jpg trong thư mục Truyện tranh như cây thư mục Hình 58.
1. Trong khung bên trái của cửa sổ This PC, em nháy chuột vào ổ đĩa D: ở khung bên trái.
2. Tìm thư mục Truyện tranh ở khung bên phải, nháy đúp chuột vào thư mục Truyện tranh để mở, ta sẽ thấy tệp Anh.jpg.
Lưu ý: Mỗi máy tính sẽ có tên tệp và thư mục khác nhau, em hãy thực hiện theo hướng dẫn cụ thể của thầy, cô giáo.
📌 Văn bản có nhiều từ nhất (grade=1)
Số câu: 28
Số từ: 491
Nội dung:
 Ngày xưa có hai chú chuột tên là Crúc và Véc sống chung với một chú Gà Trống.
Một hôm Gà Trống quét sân thấy một bông lúa mì rơi trên mặt đất.
– Crúc ơi, Véc ơi! Gà Trống gọi – Hãy xem đây, mình tìm được cái này!
Hai chú chuột cùng chạy lại nói:
– Đem đập đi!
– Nhưng ai đập? – Gà Trống hỏi.
– Không phải tôi. – Một con chuột nói.
– Cũng không phải tôi! – Con chuột kia cũng nói.
– Được, tôi sẽ đập! – Gà Trông bắt tay vào việc luôn. Đập xong lúa, Gà Trống gọi:
– Crúc ơi, Véc ơi! Hãy xem đây, mình đập được biết bao nhiêu hạt!
Hai chú chuột chạy đến, cùng bảo:
– Bây giờ mang hạt đến cối xay bột đi!
– Nhưng ai sẽ mang đi? Gà Trống hỏi.
– Không phải tôi, cũng không phải tôi! – Hai chú chuột cùng nói.
– Được, tôi sẽ mang đi – Gà Trống vác túi lúa trên vài và đến cối xay bột.
Hai con chuột lại nhảy nhót vui vẻ. Gà Trống trở về, cất tiếng gọi:
– Lại đây Crúc ! Lại đây Véc! Mình đã đem bột về đây!
Hai chú chuột vội reo:
– A! Anh Gà Trống, anh giỏi quá! Bây giờ phải nhào bột, đưa bột vào lò nướng thành bánh.
– Ai sẽ đưa bột vào lò? – Gà Trống hỏi.
Gà Trống bắt đầu nhào bột, mang củi đến và nhóm lò. Lò vừa cháy, gà đưa bột vào lò. Hai con chuột lại nhảy múa reo hò. Bánh chín, Gà Trống kéo ra, đặt lên bàn. Hai chú chuột vội chạy ngay đến, chẳng cần ai mời.
Một lần nữa, hai chú chuột lại nói:
– Không phải tôi!
– Cũng không phải tôi!
 Ồ! Đói quá! Crúc kêu lên.
– Mình thèm quá! – Véc cũng kêu lên.
Thế là hai chú chuột ngồi ngay vào bàn. Gà Trống nói:
– Đợi chút nào! Các bạn hãy nói cho biết, ai tìm ra bông lúa?
– Anh chứ ai – Cả hai cùng nói.
– Thế ai đập lúa? – Gà Trống hỏi.
– Anh đập lúa – Cả hai chuột lí nhỉ trả lời.
– Ai mang bột đến cối xay?
– Cũng lại anh – Hai con trả lời giọng càng nhỏ hơn.
– Ai nhào bột? Ai mang củi? Ai nhóm lò? Ai nướng bánh?
– Anh làm tất cả! Anh làm tất cả!
– Thế các bạn làm gì?
Biết trả lời thế nào? Crúc và Véc lúng túng, đi ra khỏi bàn. Gà Trống không giữ. Vì không nên mời kẻ lười biếng ăn bánh.

In [12]:
import pandas as pd

# ===== 1. Load dữ liệu =====
INPUT_XLSX = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\DATA_DG_main_2.xlsx"
OUTPUT_XLSX = r"E:\Project_NguyenMinhVu_2211110063\Source\datasets\dataset abstractive\DATA_DG_main_3.xlsx"

df = pd.read_excel(INPUT_XLSX)

# ===== 2. Lọc grade = 1 & publisher null =====
mask_g1 = (df["grade"] == 3) & (df["publisher"].isna())
df_g1 = df[mask_g1].copy()

# ===== 3. Hàm đếm câu & từ (NHANH – ỔN ĐỊNH) =====
def count_fast(text):
    if not isinstance(text, str) or not text.strip():
        return 0, 0

    # đếm câu (đủ chính xác cho giáo dục)
    sentences = text.replace("!", ".").replace("?", ".").split(".")
    num_sentences = len([s for s in sentences if s.strip()])

    # đếm từ
    num_words = len(text.split())

    return num_sentences, num_words

# ===== 4. Xác định các dòng cần xóa =====
drop_idx = []

for idx, row in df_g1.iterrows():
    s, w = count_fast(row["content"])
    if s > 45 or w > 650:
        drop_idx.append(idx)

# ===== 5. Xóa dòng trong df gốc =====
df = df.drop(index=drop_idx).reset_index(drop=True)

# ===== 6. Lưu file =====
df.to_excel(OUTPUT_XLSX, index=False)

print("✅ Hoàn tất lọc dữ liệu")
print(f"🗑️ Số dòng bị xóa: {len(drop_idx)}")

✅ Hoàn tất lọc dữ liệu
🗑️ Số dòng bị xóa: 1838